param location string
param profileName string
param endpointName string
param originGroupName string
param originHostName string
param originResourceId string
param tags object

resource profile 'Microsoft.Cdn/profiles@2025-06-01' = {
  name: profileName
  location: 'global'
  tags: tags
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    originResponseTimeoutSeconds: 120
  }
}

resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2026-04-01-preview' = {
  parent: profile
  name: endpointName
  location: 'global'
  tags: tags
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'ResourceGroupReuse'
    enforceMtls: 'Disabled'
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2026-04-01-preview' = {
  parent: profile
  name: originGroupName
  properties: {
    healthProbeSettings: {
      probeIntervalInSeconds: 60
      probePath: '/'
      probeProtocol: 'Https'
      probeRequestType: 'GET'
    }
    loadBalancingSettings: {
      additionalLatencyInMilliseconds: 0
      sampleSize: 4
      successfulSamplesRequired: 3
    }
    sessionAffinityState: 'Disabled'
    trafficRestorationTimeToHealedOrNewEndpointsInMinutes: 10
  }
}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2026-04-01-preview' = {
  parent: originGroup
  name: 'apim-origin'
  properties: {
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
    hostName: replace(originHostName, 'https://', '')
    httpPort: 80
    httpsPort: 443
    originHostHeader: replace(originHostName, 'https://', '')
    priority: 1
    weight: 1000
    sharedPrivateLinkResource: {
      groupId: 'gateway'
      privateLink: {
        id: originResourceId
      }
      privateLinkLocation: location
      requestMessage: 'Approve Front Door access to the API Management gateway'
      status: 'Pending'
    }
  }
}

resource route 'Microsoft.Cdn/profiles/afdEndpoints/routes@2026-04-01-preview' = {
  parent: endpoint
  name: 'api-route'
  properties: {
    enabledState: 'Enabled'
    forwardingProtocol: 'MatchRequest'
    httpsRedirect: 'Enabled'
    linkToDefaultDomain: 'Enabled'
    originGroup: {
      id: originGroup.id
    }
    patternsToMatch: [
      '/*'
    ]
    supportedProtocols: [
      'Https'
      'Http'
    ]
  }
}

output endpointName string = endpoint.name
output profileId string = profile.id
output routeId string = route.id
