import React, { useState } from 'react';
import { Check, Download, Search, ShieldCheck } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { format } from 'date-fns';
import { AdminCard, AdminPageFrame, AdminShell, AdminState, AdminStatus, AdminTable } from '../components/admin/AdminShell';
import { adminService } from '../services/admin.service';
import { bookingReference } from '../utils/bookingReference';

const displayName = (person?: { firstName: string; lastName: string; email?: string }) => person ? `${person.firstName} ${person.lastName}`.trim() : 'Unknown';
const dateLabel = (value?: string) => value ? format(new Date(value), 'MMM d, yyyy') : '—';
const statusTone = (status: string): 'green' | 'orange' | 'blue' | 'red' => ['COMPLETED', 'SUCCEEDED', 'ACCEPTED'].includes(status) ? 'green' : ['REJECTED', 'FAILED', 'CANCELLED'].includes(status) ? 'red' : status === 'PENDING' ? 'orange' : 'blue';

export const AdminVerificationPage: React.FC = () => {
    const queryClient = useQueryClient();
    const query = useQuery({ queryKey: ['adminVerification'], queryFn: adminService.getVerification });
    const mutation = useMutation({ mutationFn: ({ id, isVerified }: { id: string; isVerified: boolean }) => adminService.updateVerification(id, isVerified), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['adminVerification'] }) });
    return <AdminShell><AdminPageFrame title="Verification queue" description="Review sitter profiles before they appear in marketplace search."><AdminState loading={query.isLoading} error={query.isError}><AdminCard><div className="mb-5 flex items-center justify-between"><div><h3 className="font-display text-base font-bold">Pending applications</h3><p className="mt-1 text-xs text-slate-400">{query.data?.length || 0} profiles need review</p></div><AdminStatus tone="orange">Needs review</AdminStatus></div><AdminTable><thead className="bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-800/50"><tr><th className="px-6 py-3">Applicant</th><th className="px-4 py-3">Headline</th><th className="px-4 py-3">Submitted</th><th className="px-6 py-3 text-right">Decision</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{query.data?.map((item) => <tr key={item.id} className="text-sm hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td className="px-6 py-4"><p className="font-bold">{displayName(item.user)}</p><p className="mt-1 text-xs text-slate-400">{item.user?.email}</p></td><td className="max-w-xs px-4 py-4 text-slate-500">{item.headline || 'No headline provided'}</td><td className="px-4 py-4 text-slate-500">{dateLabel(item.createdAt)}</td><td className="px-6 py-4 text-right"><div className="flex justify-end gap-2"><button disabled={mutation.isPending} onClick={() => mutation.mutate({ id: item.id, isVerified: false })} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50 disabled:opacity-50">Keep pending</button><button disabled={mutation.isPending} onClick={() => mutation.mutate({ id: item.id, isVerified: true })} className="inline-flex items-center gap-1 rounded-lg bg-orange-500 px-3 py-2 text-xs font-bold text-white hover:bg-orange-600 disabled:opacity-50"><Check className="h-3.5 w-3.5" /> Approve</button></div></td></tr>)}</tbody></AdminTable>{!query.data?.length && <p className="py-10 text-center text-sm text-slate-400">The verification queue is clear.</p>}</AdminCard></AdminState></AdminPageFrame></AdminShell>;
};

export const AdminUsersPage: React.FC = () => {
    const [search, setSearch] = useState('');
    const query = useQuery({ queryKey: ['adminUsers', search], queryFn: () => adminService.getUsers(search) });
    return <AdminShell><AdminPageFrame title="Users & sitters" description="Manage the people and service providers using Double Paws." action={<div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users" className="h-10 w-64 rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-orange-400 dark:border-slate-800 dark:bg-slate-900" /></div>}><AdminState loading={query.isLoading} error={query.isError}><AdminCard><AdminTable><thead className="bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-800/50"><tr><th className="px-6 py-3">User</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Joined</th><th className="px-6 py-3">Account</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{query.data?.map((user) => <tr key={user.id} className="text-sm hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td className="px-6 py-4 font-bold">{displayName(user)}</td><td className="px-4 py-4 text-slate-500">{user.email}</td><td className="px-4 py-4 text-slate-500">{dateLabel(user.createdAt)}</td><td className="px-6 py-4"><AdminStatus tone="green">Active</AdminStatus></td></tr>)}</tbody></AdminTable>{!query.data?.length && <p className="py-10 text-center text-sm text-slate-400">No users match this search.</p>}</AdminCard></AdminState></AdminPageFrame></AdminShell>;
};

export const AdminBookingsSummaryPage: React.FC = () => {
    const [status, setStatus] = useState('');
    const query = useQuery({ queryKey: ['adminBookingsSummary', status], queryFn: () => adminService.getBookings({ status }) });
    return <AdminShell><AdminPageFrame title="Bookings" description="Monitor marketplace activity, service dates, and booking status." action={<select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold dark:border-slate-800 dark:bg-slate-900"><option value="">All statuses</option><option value="Pending">Pending</option><option value="Confirmed">Confirmed</option><option value="Completed">Completed</option><option value="Needs review">Needs review</option></select>}><AdminState loading={query.isLoading} error={query.isError}><AdminCard><AdminTable><thead className="bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-800/50"><tr><th className="px-6 py-3">Booking</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Sitter</th><th className="px-4 py-3">Service date</th><th className="px-4 py-3">Value</th><th className="px-6 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{query.data?.bookings.map((booking) => <tr key={booking.id} className="text-sm hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td className="px-6 py-4 font-bold">#{bookingReference(booking.id, booking.referenceNumber)}</td><td className="px-4 py-4">{displayName(booking.owner)}</td><td className="px-4 py-4 text-slate-500">{displayName(booking.sitter?.user)}</td><td className="px-4 py-4 text-slate-500">{dateLabel(booking.startDate)}</td><td className="px-4 py-4 font-bold">€{Number(booking.totalPrice || 0).toFixed(2)}</td><td className="px-6 py-4"><AdminStatus tone={statusTone(booking.status)}>{booking.status}</AdminStatus></td></tr>)}</tbody></AdminTable>{!query.data?.bookings.length && <p className="py-10 text-center text-sm text-slate-400">No bookings found.</p>}</AdminCard></AdminState></AdminPageFrame></AdminShell>;
};

export const AdminPaymentsPage: React.FC = () => {
    const query = useQuery({ queryKey: ['adminPayments'], queryFn: adminService.getPayments });
    return <AdminShell><AdminPageFrame title="Payments" description="Track payment status and marketplace revenue." action={<button className="inline-flex h-10 items-center gap-2 rounded-xl bg-slate-900 px-3 text-sm font-semibold text-white"><Download className="h-4 w-4" /> Export</button>}><AdminState loading={query.isLoading} error={query.isError}><AdminCard><AdminTable><thead className="bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-800/50"><tr><th className="px-6 py-3">Payment</th><th className="px-4 py-3">Payer</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Created</th><th className="px-6 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{query.data?.map((payment) => <tr key={payment.id} className="text-sm hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td className="px-6 py-4 font-bold">#{payment.id.slice(0, 8)}</td><td className="px-4 py-4">{displayName(payment.owner)}</td><td className="px-4 py-4 font-bold">{payment.currency.toUpperCase()} {(payment.amount / 100).toFixed(2)}</td><td className="px-4 py-4 text-slate-500">{dateLabel(payment.createdAt)}</td><td className="px-6 py-4"><AdminStatus tone={statusTone(payment.status)}>{payment.status}</AdminStatus></td></tr>)}</tbody></AdminTable>{!query.data?.length && <p className="py-10 text-center text-sm text-slate-400">No payments found.</p>}</AdminCard></AdminState></AdminPageFrame></AdminShell>;
};

export const AdminReportsPage: React.FC = () => {
    const query = useQuery({ queryKey: ['adminReports'], queryFn: adminService.getReports });
    return <AdminShell><AdminPageFrame title="Reports" description="A clear view of growth, revenue, and operational health." action={<button className="inline-flex h-10 items-center gap-2 rounded-xl bg-slate-900 px-3 text-sm font-semibold text-white"><Download className="h-4 w-4" /> Export report</button>}><AdminState loading={query.isLoading} error={query.isError}>{query.data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Users', query.data.metrics.userCount], ['Bookings', query.data.metrics.bookingCount], ['Revenue', `€${query.data.metrics.grossRevenue.toFixed(0)}`], ['Completion', `${query.data.metrics.completionRate.toFixed(1)}%`]].map(([label, value]) => <AdminCard key={String(label)}><p className="text-sm font-semibold text-slate-400">{label}</p><p className="mt-3 font-display text-3xl font-bold">{value}</p></AdminCard>)}</div><AdminCard><h3 className="font-display text-base font-bold">Last 30 days</h3><p className="mt-1 text-xs text-slate-400">Daily bookings and revenue activity</p><div className="mt-6 grid grid-cols-10 gap-2 sm:grid-cols-15 lg:grid-cols-30">{query.data.chart.map((item) => <div key={item.date} title={`${dateLabel(item.date)} · ${item.bookings} bookings`} className="group flex h-40 items-end rounded-lg bg-slate-50 p-1 dark:bg-slate-800"><div className="w-full rounded-md bg-orange-400 transition-all group-hover:bg-orange-500" style={{ height: `${Math.max(8, Math.min(100, item.bookings * 18))}%` }} /></div>)}</div></AdminCard></>}</AdminState></AdminPageFrame></AdminShell>;
};

export const AdminSettingsPage: React.FC = () => {
    const query = useQuery({ queryKey: ['adminSettings'], queryFn: adminService.getSettings });
    return <AdminShell><AdminPageFrame title="Settings" description="Review production integrations and operational configuration."><AdminState loading={query.isLoading} error={query.isError}>{query.data && <div className="grid gap-6 lg:grid-cols-2"><AdminCard><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-500" /><h3 className="font-display text-base font-bold">Production services</h3></div><div className="mt-5 space-y-4">{[['Environment', query.data.environment], ['Payments', query.data.paymentsEnabled ? 'Enabled' : 'Not configured'], ['Google login', query.data.googleLoginEnabled ? 'Enabled' : 'Not configured']].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between border-b border-slate-100 pb-3 text-sm dark:border-slate-800"><span className="text-slate-500">{label}</span><span className="font-semibold">{value}</span></div>)}</div></AdminCard><AdminCard><h3 className="font-display text-base font-bold">Email configuration</h3><p className="mt-1 text-xs text-slate-400">The sender used for transactional emails.</p><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-800"><p className="font-semibold">{query.data.emailFrom || 'Not configured'}</p><p className="mt-1 text-xs text-slate-500">Links: {query.data.emailAppUrl || 'Not configured'}</p></div></AdminCard></div>}</AdminState></AdminPageFrame></AdminShell>;
};

export const AdminAuditPage: React.FC = () => {
    const query = useQuery({ queryKey: ['adminAudit'], queryFn: adminService.getAudit });
    return <AdminShell><AdminPageFrame title="Audit log" description="Recent platform events for accountability and support investigations."><AdminState loading={query.isLoading} error={query.isError}><AdminCard><div className="space-y-1">{query.data?.map((event, index) => <div key={`${event.createdAt}-${index}`} className="flex items-center gap-4 rounded-xl px-3 py-4 hover:bg-slate-50 dark:hover:bg-slate-800"><span className="h-2 w-2 rounded-full bg-orange-500" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{event.label}</p><p className="mt-1 text-xs uppercase tracking-wider text-slate-400">{event.type}</p></div><time className="text-xs text-slate-400">{dateLabel(event.createdAt)}</time></div>)}</div>{!query.data?.length && <p className="py-10 text-center text-sm text-slate-400">No audit events yet.</p>}</AdminCard></AdminState></AdminPageFrame></AdminShell>;
};
