import React, { useState } from 'react';
import { Check, Download, Search, ShieldCheck } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { format } from 'date-fns';
import { AdminCard, AdminPageFrame, AdminShell, AdminState, AdminStatus, AdminTable } from '../components/admin/AdminShell';
import { adminService } from '../services/admin.service';

const name = (p?: { firstName: string; lastName: string; email?: string }) => p ? `${p.firstName} ${p.lastName}`.trim() : 'Unknown';
const date = (v?: string) => v ? format(new Date(v), 'MMM d, yyyy') : '—';
const tone = (s: string): 'green' | 'orange' | 'blue' | 'red' => ['COMPLETED', 'SUCCEEDED', 'ACCEPTED'].includes(s) ? 'green' : ['REJECTED', 'FAILED', 'CANCELLED'].includes(s) ? 'red' : s === 'PENDING' ? 'orange' : 'blue';
const SearchBox: React.FC<{ value: string; placeholder: string; onChange: (value: string) => void }> = ({ value, placeholder, onChange }) => <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-10 w-64 rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-orange-400 dark:border-slate-800 dark:bg-slate-900" /></div>;
const Pages: React.FC<{ data?: { page: number; totalPages: number; total: number }; setPage: (p: number) => void }> = ({ data, setPage }) => data ? <div className="flex items-center justify-between border-t border-slate-100 px-6 py-4 text-xs text-slate-500"><span>{data.total} result{data.total === 1 ? '' : 's'}</span><div className="flex items-center gap-2"><button disabled={data.page <= 1} onClick={() => setPage(data.page - 1)} className="rounded-lg border px-3 py-2 font-semibold disabled:opacity-40">Previous</button><span className="px-2 font-semibold">Page {data.page} of {data.totalPages}</span><button disabled={data.page >= data.totalPages} onClick={() => setPage(data.page + 1)} className="rounded-lg border px-3 py-2 font-semibold disabled:opacity-40">Next</button></div></div> : null;

export const AdminVerificationPage: React.FC = () => { const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const qc = useQueryClient(); const q = useQuery({ queryKey: ['adminVerification', search, page], queryFn: () => adminService.getVerification({ search, page }) }); const m = useMutation({ mutationFn: ({ id, ok }: { id: string; ok: boolean }) => adminService.updateVerification(id, ok), onSuccess: () => qc.invalidateQueries({ queryKey: ['adminVerification'] }) }); return <AdminShell><AdminPageFrame title="Verification queue" description="Review sitter profiles before they appear in marketplace search." action={<SearchBox value={search} placeholder="Search applicants" onChange={(v) => { setSearch(v); setPage(1); }} />}><AdminState loading={q.isLoading} error={q.isError}><AdminCard><div className="mb-5 flex justify-between"><div><h3 className="font-display text-base font-bold">Pending applications</h3><p className="mt-1 text-xs text-slate-400">{q.data?.total || 0} profiles need review</p></div><AdminStatus tone="orange">Needs review</AdminStatus></div><AdminTable><thead><tr><th className="px-6 py-3 text-left">Applicant</th><th className="px-4 py-3 text-left">Headline</th><th className="px-4 py-3 text-left">Submitted</th><th className="px-6 py-3 text-right">Decision</th></tr></thead><tbody className="divide-y divide-slate-100">{q.data?.items.map((s) => <tr key={s.id} className="text-sm"><td className="px-6 py-4"><b>{name(s.user)}</b><p className="text-xs text-slate-400">{s.user?.email}</p></td><td className="px-4 py-4 text-slate-500">{s.headline || 'No headline provided'}</td><td className="px-4 py-4 text-slate-500">{date(s.createdAt)}</td><td className="px-6 py-4 text-right"><button onClick={() => m.mutate({ id: s.id, ok: true })} className="inline-flex items-center gap-1 rounded-lg bg-orange-500 px-3 py-2 text-xs font-bold text-white"><Check className="h-3.5 w-3.5" /> Approve</button></td></tr>)}</tbody></AdminTable><Pages data={q.data} setPage={setPage} /></AdminCard></AdminState></AdminPageFrame></AdminShell>; };
export const AdminUsersPage: React.FC = () => { const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const q = useQuery({ queryKey: ['adminUsers', search, page], queryFn: () => adminService.getUsers({ search, page }) }); return <AdminShell><AdminPageFrame title="Users & sitters" description="Manage the people and service providers using Double Paws." action={<SearchBox value={search} placeholder="Search users" onChange={(v) => { setSearch(v); setPage(1); }} />}><AdminState loading={q.isLoading} error={q.isError}><AdminCard><AdminTable><thead><tr><th className="px-6 py-3 text-left">User</th><th className="px-4 py-3 text-left">Email</th><th className="px-4 py-3 text-left">Joined</th><th className="px-6 py-3 text-left">Account</th></tr></thead><tbody className="divide-y divide-slate-100">{q.data?.items.map((u) => <tr key={u.id} className="text-sm"><td className="px-6 py-4 font-bold">{name(u)}</td><td className="px-4 py-4 text-slate-500">{u.email}</td><td className="px-4 py-4 text-slate-500">{date(u.createdAt)}</td><td className="px-6 py-4"><AdminStatus tone="green">Active</AdminStatus></td></tr>)}</tbody></AdminTable><Pages data={q.data} setPage={setPage} /></AdminCard></AdminState></AdminPageFrame></AdminShell>; };
export const AdminBookingsSummaryPage: React.FC = () => <AdminShell><AdminPageFrame title="Bookings" description="Use the full bookings screen for API-backed filters and pagination."><AdminCard><p className="text-sm text-slate-500">Open the bookings workspace to review and filter all bookings.</p></AdminCard></AdminPageFrame></AdminShell>;
export const AdminPaymentsPage: React.FC = () => { const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const q = useQuery({ queryKey: ['adminPayments', search, page], queryFn: () => adminService.getPayments({ search, page }) }); return <AdminShell><AdminPageFrame title="Payments" description="Track payment status and marketplace revenue." action={<div className="flex gap-2"><SearchBox value={search} placeholder="Search payments" onChange={(v) => { setSearch(v); setPage(1); }} /><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-slate-900 px-3 text-sm font-semibold text-white"><Download className="h-4 w-4" /> Export</button></div>}><AdminState loading={q.isLoading} error={q.isError}><AdminCard><AdminTable><thead><tr><th className="px-6 py-3 text-left">Payment</th><th className="px-4 py-3 text-left">Payer</th><th className="px-4 py-3 text-left">Amount</th><th className="px-4 py-3 text-left">Created</th><th className="px-6 py-3 text-left">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{q.data?.items.map((p) => <tr key={p.id} className="text-sm"><td className="px-6 py-4 font-bold">#{p.id.slice(0, 8)}</td><td className="px-4 py-4">{name(p.owner)}</td><td className="px-4 py-4 font-bold">{p.currency.toUpperCase()} {(p.amount / 100).toFixed(2)}</td><td className="px-4 py-4 text-slate-500">{date(p.createdAt)}</td><td className="px-6 py-4"><AdminStatus tone={tone(p.status)}>{p.status}</AdminStatus></td></tr>)}</tbody></AdminTable><Pages data={q.data} setPage={setPage} /></AdminCard></AdminState></AdminPageFrame></AdminShell>; };
export const AdminReportsPage: React.FC = () => { const q = useQuery({ queryKey: ['adminReports'], queryFn: adminService.getReports }); return <AdminShell><AdminPageFrame title="Reports" description="A clear view of growth, revenue, and operational health."><AdminState loading={q.isLoading} error={q.isError}>{q.data && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Users', q.data.metrics.userCount], ['Bookings', q.data.metrics.bookingCount], ['Revenue', `€${q.data.metrics.grossRevenue.toFixed(0)}`], ['Completion', `${q.data.metrics.completionRate.toFixed(1)}%`]].map(([l, v]) => <AdminCard key={String(l)}><p className="text-sm text-slate-400">{l}</p><p className="mt-3 text-3xl font-bold">{v}</p></AdminCard>)}</div>}</AdminState></AdminPageFrame></AdminShell>; };
export const AdminSettingsPage: React.FC = () => { const q = useQuery({ queryKey: ['adminSettings'], queryFn: adminService.getSettings }); return <AdminShell><AdminPageFrame title="Settings" description="Review production integrations and operational configuration."><AdminState loading={q.isLoading} error={q.isError}>{q.data && <AdminCard><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-500" /><h3 className="font-display text-base font-bold">Production services</h3></div><div className="mt-5 space-y-4">{[['Environment', q.data.environment], ['Payments', q.data.paymentsEnabled ? 'Enabled' : 'Not configured'], ['Google login', q.data.googleLoginEnabled ? 'Enabled' : 'Not configured']].map(([l, v]) => <div key={String(l)} className="flex justify-between border-b pb-3 text-sm"><span className="text-slate-500">{l}</span><b>{v}</b></div>)}</div></AdminCard>}</AdminState></AdminPageFrame></AdminShell>; };
export const AdminAuditPage: React.FC = () => { const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const q = useQuery({ queryKey: ['adminAudit', search, page], queryFn: () => adminService.getAudit({ search, page }) }); return <AdminShell><AdminPageFrame title="Audit log" description="Recent platform events for accountability and support investigations." action={<SearchBox value={search} placeholder="Search audit log" onChange={(v) => { setSearch(v); setPage(1); }} />}><AdminState loading={q.isLoading} error={q.isError}><AdminCard><div className="space-y-1">{q.data?.items.map((e, i) => <div key={`${e.createdAt}-${i}`} className="flex items-center gap-4 rounded-xl px-3 py-4"><span className="h-2 w-2 rounded-full bg-orange-500" /><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{e.label}</p><p className="mt-1 text-xs uppercase text-slate-400">{e.type}</p></div><time className="text-xs text-slate-400">{date(e.createdAt)}</time></div>)}</div><Pages data={q.data} setPage={setPage} /></AdminCard></AdminState></AdminPageFrame></AdminShell>; };
