import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CheckCircle, Heart, Home, Mail, Shield, Sparkles, Stethoscope, Users } from 'lucide-react';

const services = [
    { slug: 'daycare', title: 'Daycare', icon: Heart, description: 'A fun, caring day with a trusted sitter while you are away.' },
    { slug: 'boarding', title: 'Boarding', icon: Home, description: 'A comfortable home away from home, with overnight care tailored to your pet.' },
    { slug: 'grooming', title: 'Grooming', icon: Sparkles, description: 'Keep your pet happy, healthy, and feeling their best with gentle grooming.' },
    { slug: 'training', title: 'Training', icon: Users, description: 'Positive, practical support to help your pet build confidence and good habits.' },
    { slug: 'veterinary', title: 'Veterinary care', icon: Stethoscope, description: 'Extra peace of mind with care plans that consider your pet\'s health needs.' },
];

const Page: React.FC<{ eyebrow: string; title: string; children: React.ReactNode }> = ({ eyebrow, title, children }) => <div className="bg-gradient-to-b from-orange-50/70 via-white to-white"><section className="mx-auto max-w-6xl px-4 py-20 text-center sm:px-6 lg:px-8"><p className="font-semibold uppercase tracking-[0.2em] text-primary">{eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl font-display text-4xl font-bold tracking-tight text-slate-950 sm:text-6xl">{title}</h1>{children}</section></div>;

const aboutFeatures: Array<[string, React.ElementType, string]> = [['Trust first', Shield, 'Verified profiles and secure payments help you book with confidence.'], ['Pets come first', Heart, 'Every experience is designed around comfort, safety, and individual needs.'], ['Real support', Users, 'Our community is here to make every stay smoother for pets and people.']];
export const AboutPage: React.FC = () => <Page eyebrow="About Double Paws" title="Care that feels like home."><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">We connect pet parents with caring, trusted sitters who treat every animal like family. From the first message to the final cuddle, we make pet care simple and reassuring.</p><div className="mx-auto mt-12 grid max-w-4xl gap-5 text-left sm:grid-cols-3">{aboutFeatures.map(([title, Icon, text]) => <div key={title} className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm"><Icon className="h-7 w-7 text-primary" /><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></Page>;

export const ServicesPage: React.FC = () => <Page eyebrow="Our services" title="The right care for every pet personality."><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Find flexible care from local sitters, compare their profiles, and choose the support that fits your pet and your schedule.</p><div className="mx-auto mt-12 grid max-w-5xl gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(({ slug, title, icon: Icon, description }) => <Link key={slug} to={`/services/${slug}`} className="group rounded-3xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-1 hover:border-primary/40 hover:shadow-lg"><Icon className="h-8 w-8 text-primary" /><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Explore care <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></Page>;

export const PricingPage: React.FC = () => <Page eyebrow="Simple pricing" title="Great care, clear rates."><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Sitters set their own rates based on their experience and services. You see the price before requesting a booking, with no hidden surprises.</p><div className="mx-auto mt-12 grid max-w-4xl gap-5 text-left md:grid-cols-3">{[['Daycare', 'From €20', 'Flexible daytime care'], ['Boarding', 'From €30', 'Overnight peace of mind'], ['House sitting', 'From €50', 'Care in your own home']].map(([title, price, text]) => <div key={title} className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-sm font-semibold text-orange-300">{title}</p><p className="mt-4 font-display text-3xl font-bold">{price}</p><p className="mt-2 text-sm text-slate-300">{text}</p><CheckCircle className="mt-8 h-6 w-6 text-emerald-400" /></div>)}</div><Link to="/search" className="mt-12 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 font-bold text-white shadow-lg shadow-primary/20">Find a sitter <ArrowRight className="h-4 w-4" /></Link></Page>;

export const ContactPage: React.FC = () => <Page eyebrow="We are here to help" title="Let’s make pet care easier."><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Have a question about finding a sitter, becoming one, or managing a booking? Our team would love to hear from you.</p><div className="mx-auto mt-12 max-w-xl rounded-3xl border border-orange-100 bg-white p-8 text-left shadow-sm"><Mail className="h-8 w-8 text-primary" /><h2 className="mt-5 font-display text-2xl font-bold">Contact our support team</h2><p className="mt-2 text-slate-500">Send us an email and we will get back to you as soon as possible.</p><a href="mailto:support@doublepaws24.com" className="mt-6 inline-flex items-center gap-2 font-bold text-primary">support@doublepaws24.com <ArrowRight className="h-4 w-4" /></a></div></Page>;

export const ServiceDetailPage: React.FC = () => { const { slug } = useParams(); const service = services.find((item) => item.slug === slug) || services[0]; const Icon = service.icon; return <Page eyebrow="Double Paws services" title={`${service.title} made easier.`}><div className="mx-auto mt-8 max-w-2xl rounded-3xl border border-orange-100 bg-white p-8 shadow-sm"><Icon className="mx-auto h-12 w-12 text-primary" /><p className="mt-5 text-lg leading-8 text-slate-600">{service.description} Browse available sitters, review their experience and photos, then message them before you book.</p><Link to={`/search?service=${service.slug}`} className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 font-bold text-white">Find {service.title.toLowerCase()} <ArrowRight className="h-4 w-4" /></Link></div></Page>; };
